#!/usr/bin/env bash
set -euo pipefail

DATA_DIR="${LANGFLOW_CONFIG_DIR:-/opt/render/project/src/langflow-data}"
mkdir -p "$DATA_DIR"
mkdir -p /opt/render/project/src/langflow-data

export LANGFLOW_HOST="${LANGFLOW_HOST:-0.0.0.0}"
export LANGFLOW_PORT="${PORT:-${LANGFLOW_PORT:-7860}}"
export LANGFLOW_LOG_LEVEL="${LANGFLOW_LOG_LEVEL:-info}"
export DO_NOT_TRACK="${DO_NOT_TRACK:-true}"
export LANGFLOW_BACKEND_ONLY="${LANGFLOW_BACKEND_ONLY:-true}"
export LANGFLOW_CREATE_STARTER_PROJECTS="${LANGFLOW_CREATE_STARTER_PROJECTS:-false}"
export LANGFLOW_UPDATE_STARTER_PROJECTS="${LANGFLOW_UPDATE_STARTER_PROJECTS:-false}"
export LANGFLOW_LAZY_LOAD_COMPONENTS="${LANGFLOW_LAZY_LOAD_COMPONENTS:-true}"
export LANGFLOW_STORE="${LANGFLOW_STORE:-false}"
export LANGFLOW_MCP_SERVER_ENABLED="${LANGFLOW_MCP_SERVER_ENABLED:-false}"
export LANGFLOW_MCP_COMPOSER_ENABLED="${LANGFLOW_MCP_COMPOSER_ENABLED:-false}"
export LANGFLOW_ADD_PROJECTS_TO_MCP_SERVERS="${LANGFLOW_ADD_PROJECTS_TO_MCP_SERVERS:-false}"
export LANGFLOW_DEVELOPER_API_ENABLED="${LANGFLOW_DEVELOPER_API_ENABLED:-false}"
export LANGFLOW_OPEN_BROWSER="${LANGFLOW_OPEN_BROWSER:-false}"

printf 'Starting Langflow ASGI backend on %s:%s\n' "$LANGFLOW_HOST" "$LANGFLOW_PORT"
printf 'Startup flags: starter_projects=%s store=%s mcp_server=%s lazy_load=%s\n' \
  "$LANGFLOW_CREATE_STARTER_PROJECTS" "$LANGFLOW_STORE" "$LANGFLOW_MCP_SERVER_ENABLED" "$LANGFLOW_LAZY_LOAD_COMPONENTS"

exec python -m uvicorn render_app:create_app \
  --factory \
  --host "$LANGFLOW_HOST" \
  --port "$LANGFLOW_PORT" \
  --log-level "$LANGFLOW_LOG_LEVEL"
